################################################################################
# ENVIRONMENT TEMPLATES
################################################################################

# can't merge arrays in YAML so we have to duplicate stuff between 36 adn 37
# and include all variables that are relevant across all operating systems
env_py36: &env_py36
  env:
    - PYTHON_VERSION=3.6.8
    - PY_MM=36
    - TOXENV=py${PY_MM}
    - PATH=/c/Python36/Lib/site-packages/pupil_pthreads_win/data/lib/x64:/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH
env_py37: &env_py37
  env:
    - PYTHON_VERSION=3.7.4
    - PY_MM=37
    - TOXENV=py${PY_MM}
    - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH


################################################################################
# OS JOB TEMPLATES
################################################################################

osx_base_job: &osx_base_job
  os: osx
  osx_image: xcode6.4
  language: sh
  before_install:
    - brew update && brew upgrade pyenv
    - pyenv install -s $PYTHON_VERSION
    - export PYENV_VERSION=$PYTHON_VERSION
    - export PATH="/Users/travis/.pyenv/shims:${PATH}"
    - pip3 install --upgrade pip
  install:
    - pip3 install -r requirements_dev.txt
    - python3 ./setup.py bdist_wheel

win_base_job: &win_base_job
  os: windows
  language: sh
  before_install:
    - chmod +x ./.travis/print_path.sh
    - ./.travis/print_path.sh
    - choco install python --version $PYTHON_VERSION
    - python -m pip install --upgrade pip
  install:
    - python -m pip install -r requirements_dev.txt
    - choco install vs2010.shellintegratedredist
    - choco install vcredist2010
    # - python ./setup.py bdist_wheel -G "Visual Studio 15 2017 Win64"
    - python ./setup.py install -G "Visual Studio 15 2017 Win64"
  script:
    - python -c "from pupil_apriltags import Detector; d = Detector()"

ubuntu_base_job: &ubuntu_base_job
  os: linux
  services: docker
  before_install:
    - docker pull quay.io/pypa/manylinux2010_x86_64
  install:
    - chmod +x ./.travis/manylinux_build_wheel.sh
    - >
      docker run --rm
      -v `pwd`:/io
      quay.io/pypa/manylinux2010_x86_64
      /io/.travis/manylinux_build_wheel.sh
      $PY_MM

ubuntu_trusty_base_job: &ubuntu_trusty_base_job
  <<: *ubuntu_base_job
  dist: trusty
  before_script:
    # update pyenv
    - pushd /opt/pyenv/plugins/python-build/../..
    - git fetch && git fetch --tags
    - git checkout v1.2.13
    - popd
    # install python
    # NOTE: does not work for 3.7.4 out of the box currently!
    - pyenv install -s $PYTHON_VERSION
    - pyenv global $PYTHON_VERSION
    - pip3 install --upgrade pip
    - pip3 install -r requirements_dev.txt

ubuntu_bionic_base_job: &ubuntu_bionic_base_job
  <<: *ubuntu_base_job
  dist: bionic
  # bionic has newest python available via travis
  language: python
  before_script:
    - pip3 install --upgrade pip
    - pip3 install -r requirements_dev.txt
  

################################################################################
# DEFINE JOB MATRIX
################################################################################

matrix:
  include:
    # - name: "Python 3.6.8 on OSX 10.10 (xcode6.4)"
    #   <<: *osx_base_job
    #   <<: *env_py36

    # - name: "Python 3.7.4 on OSX 10.10 (xcode6.4)"
    #   <<: *osx_base_job
    #   <<: *env_py37

    - name: "Python 3.6.8 on Windows"
      <<: *win_base_job
      <<: *env_py36
    
    # - name: "Python 3.7.4 on Windows"
    #   <<: *win_base_job
    #   <<: *env_py37

    # - name: "Python 3.6.8 on Ubuntu 14.04 (using manylinux wheel)"
    #   <<: *ubuntu_trusty_base_job
    #   <<: *env_py36

    # - name: "Python 3.6.8 on Ubuntu 18.04 (using manylinux wheel)"
    #   <<: *ubuntu_bionic_base_job
    #   python: 3.6.8
    #   <<: *env_py36
    
    # - name: "Python 3.7.4 on Ubuntu 18.04 (using manylinux wheel)"
    #   <<: *ubuntu_bionic_base_job
    #   python: 3.7.4
    #   <<: *env_py37


################################################################################
# RUN AND DEPLOY (OS INDEPENDENT)
################################################################################

# script:
#   - tox --installpkg ./dist/pupil_apriltags*.whl || true

deploy_template: &deploy_template
  on:
    # tags: true
    branch: travis_testing
  skip_cleanup: true

deploy:
  - provider: releases
    <<: *deploy_template
    api_key: $GitHubOAUTH
    file_glob: true
    file: "./dist/pupil_apriltags*.whl"
  # - provider: script
  #   <<: *deploy_template
  #   script: bash ./.travis/pypi_deploy.sh
